### ISSUE TITLE
HTTP（非TLS）サイト, mixed-contentなサイトを開くことができない

### ISSUE THREAD

**Issue by kotofurumiya** [nhiroyasu/SlideOver-for-macOS#5]
## 現象

TLSが有効でないサイト、つまりいまだに `http://` であるサイトを開くことができません。
TLSが有効でもmixed contentなサイトも開けない気がしていますが、こちらは確証を持てていません。

おそらくWebKitのデフォルト設定では許容しないようになっているのだと思います。
歴史あるプラットフォームや古い技術サイトなどはHTTPのままであることも多いので、対応いただけると嬉しいです。

開けない一例: http://marupeke296.com/index.html
HTTPSなのに開けない一例: https://www.mbga.jp/

## 環境

- mac mini（M1）
- macOS Monterey 12.3.1
- セキュリティソフト: なし
- プロクシ/VPNなど: なし

## ログ

ログはこれだと思います。

```
0x13284b018 - [pageProxyID=6, webPageID=7, PID=31786] WebPageProxy::didFailProvisionalLoadForFrame: frameID=4, domain=<private>, code=-1022, isMainFrame=1
```

<img width="809" alt="スクリーンショット 2022-04-30 17 56 57" src="https://user-images.githubusercontent.com/3391006/166099013-2f8d6884-425b-42bf-8d83-c0a13941c774.png">

**Comment by nhiroyasu** [comment]
@kotofurumiya  
Issueありがとうございます！
確かにHTTPSのサイトしか開けないようになっていました 🙏 
次バージョンで対応しますね 🙇
